-- Optional one-time renames / cleanup for `cards` (adjust to your history):
--
-- If you still have `single_column` from an old attempt, you can drop it:
-- ALTER TABLE public.cards DROP COLUMN IF EXISTS single_column;
--
-- If you renamed `is_inverted` → `use_single_column` in the database, the app expects:
--   use_single_column boolean NOT NULL DEFAULT false
-- (API maps JSON `singleColumn` ↔ `use_single_column`.)
